# Generated by Django 3.0.8 on 2020-08-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acharya', '0002_auto_20200715_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='icon',
            field=models.FileField(upload_to='../media/'),
        ),
    ]
